spring:
  config:
    import: optional:configserver:http://138.2.126.249:8081
  cloud:
    config:
      name: aws
      profile: jwt

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.tutorial: debug

jwt:
  secret: ${JWT_SECRET_KEY}

encrypt:
  key: ${ENCRYPT_KEY}